/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panel;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Component;
import java.awt.Window;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.sql.Statement;
import javax.swing.JOptionPane;
import pages.Setting;
import static parkspace_v2.Func.stringToInt;
import parkspace_v2.Koneksi;

/**
 *
 * @author cyber
 */
public class AddSetting extends javax.swing.JFrame {

    /**
     * Creates new form AddSetting
     */
    public AddSetting() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaV = new javax.swing.JTextField();
        hargaV = new javax.swing.JTextField();
        slotV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Setting");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(namaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 40));
        jPanel1.add(hargaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 350, 40));
        jPanel1.add(slotV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 350, 40));

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String pesan = "";
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "INSERT INTO vehicle (nama, harga, slot) VALUES (?, ?, ?)";
            PreparedStatement preparedStatement = c.prepareStatement(sql);

            // Gantilah dengan pengambilan nilai dari komponen teks yang sesuai
            preparedStatement.setString(1, namaV.getText());
            preparedStatement.setString(2, ""+stringToInt(hargaV.getText())+"");
            preparedStatement.setString(3, ""+stringToInt(slotV.getText())+"");

            int result = preparedStatement.executeUpdate();
            int jumlahSlot = stringToInt(slotV.getText());

            if (result > 0) {
                String sqlGetLastInsertedID = "SELECT LAST_INSERT_ID()";
                Statement stmts = c.createStatement();
                ResultSet rs = stmts.executeQuery(sqlGetLastInsertedID);

                int lastInsertedID = -1;

                if (rs.next()) {
                    lastInsertedID = rs.getInt(1);
                }
                
                for(int i = 1; i <= jumlahSlot; i++){
                    String sql2 = "INSERT INTO space (type, noParkir, status) VALUES (?, ?, ?)";
                    PreparedStatement preparedStatement2 = c.prepareStatement(sql2);
                    
                    preparedStatement2.setInt(1, lastInsertedID);
                    preparedStatement2.setString(2, ""+i+"");
                    preparedStatement2.setInt(3, 0);
                    preparedStatement2.executeUpdate();
                }
                
                pesan = "berhasil";
            } else {
                pesan = "gagal";
            }
            
            Window window = SwingUtilities.getWindowAncestor((Component) evt.getSource());
            if (window instanceof JFrame) {
                ((JFrame) window).dispose();
            }
            
            Setting.table(null);

        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        JOptionPane.showMessageDialog(null, "Data "+ pesan +" ditambah", pesan, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void init() {
        namaV.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Bus");
        hargaV.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "10.000");
        slotV.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "3");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hargaV;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namaV;
    private javax.swing.JTextField slotV;
    // End of variables declaration//GEN-END:variables

}
