/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package panel;

import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Component;
import java.awt.Window;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pages.Admin;
import parkspace_v2.Koneksi;

/**
 *
 * @author cyber
 */
public class UpdateAdmin extends javax.swing.JFrame {
    private int id;


    /**
     * Creates new form AddSetting
     */
    public UpdateAdmin(int id) {
        this.id = id;
        initComponents();
        fieldUpdate();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        namaV = new javax.swing.JTextField();
        Ipassword = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 220));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(370, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Update Admin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel1.add(namaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, 40));
        jPanel1.add(Ipassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 350, 40));

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Connection c = Koneksi.getKoneksi(); 
        String pesan = "";
        try {
            c.setAutoCommit(false);
            
            String updateVehicleSQL = "UPDATE admin SET username = ?, password = ? WHERE id = ?";
            PreparedStatement preparedStatement = c.prepareStatement(updateVehicleSQL);
            preparedStatement.setString(1, namaV.getText());
            preparedStatement.setString(2, Ipassword.getText());
            preparedStatement.setInt(3, id);
            int result = preparedStatement.executeUpdate();

            if (result > 0) {
                c.commit();
                pesan = "Berhasil";
            } else {
                c.rollback();
                pesan = "Gagal";
            }
            
            
            Window window = SwingUtilities.getWindowAncestor((Component) evt.getSource());
            if (window instanceof JFrame) {
                ((JFrame) window).dispose();
            }
            
            try {
                Admin.tables(null);
            } catch (SQLException ex) {
                Logger.getLogger(UpdateAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(null, pesan + "Memperbarui Data", pesan, JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error Database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void init() {
        namaV.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukan nama..");
        Ipassword.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Masukan password..");
    }
    
    public void fieldUpdate(){
         try {
            Connection c = Koneksi.getKoneksi();
            String sql = "SELECT username, password FROM admin WHERE id = ?";
            PreparedStatement preparedStatement = c.prepareStatement(sql);
            preparedStatement.setInt(1, id);

            ResultSet rs = preparedStatement.executeQuery();

            if (rs.next()) {
                String nama = rs.getString("username");
                namaV.setText(nama); 
                
                String pass = rs.getString("password");
                Ipassword.setText(pass);
            }
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ipassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namaV;
    // End of variables declaration//GEN-END:variables

}
